import type { AdminRequest, AdminRequestList, AdminRequestParams, NearbyMerchandiser } from "./types";

const statuses = ["draft", "pending", "failed", "in_progress", "canceled", "in_review", "accepted", "rejected", "reopened"] as const;
const services = [{ id: "1", name: "Freshness Report", price: 50, duration: "30 min", brand: "Pepsico", subBrand: "Pepsi Diet", category: "Soft Drinks", subCategory: "Diet Drinks", guideline: "Planogram", products: [{ id: "1", name: "Diet Drinks", sku: "123SKU", quantity: 234, expiryDate: "2026-05-12" }, { id: "2", name: "Diet Drinks", sku: "123SKU", quantity: 65, expiryDate: "2026-05-12" }] }];
let records: AdminRequest[] = statuses.map((status, index) => ({ id: `REQ-${4521 + index}`, companyName: "TechCorp", companyCountry: "Saudi Arabia", companyDeleted: index > 6, createdAt: "2026-05-22T10:30:00", storeName: "Dammam", price: 330, status, location: "Panda Hypermarket", assignedBy: "Mohamed Ali", worker: index > 1 ? "Mohamed Ali" : undefined, executionDate: "2026-05-25", timeWindow: "09:00 AM", expiresAt: "2026-05-25T12:00:00", services }));

export async function getAdminRequests(params: AdminRequestParams): Promise<AdminRequestList> { const search = params.search?.toLowerCase(); const filtered = records.filter((item) => (!search || [item.id, item.companyName, item.storeName].some((value) => value.toLowerCase().includes(search))) && (!params.status || params.status === "all" || item.status === params.status) && (params.companyDeleted == null || item.companyDeleted === params.companyDeleted)); const start = (params.page - 1) * params.perPage; return { data: filtered.slice(start, start + params.perPage), stats: { total: records.length, pending: records.filter((item) => item.status === "pending").length, inProgress: records.filter((item) => item.status === "in_progress").length, rejected: records.filter((item) => item.status === "rejected").length, completedWeek: 0, commission: records.reduce((sum, item) => sum + item.price, 0) }, meta: { page: params.page, lastPage: Math.max(1, Math.ceil(filtered.length / params.perPage)) } }; }
export async function getAdminRequest(id: string) { return records.find((item) => item.id === id) ?? null; }
export async function getNearbyMerchandisers(): Promise<NearbyMerchandiser[]> { return Array.from({ length: 5 }, (_, index) => ({ id: String(index + 1), name: "Mohammed Hassan", phone: "+966 55 234 5678", distanceKm: 2.3 + index, tasks: 145, rating: 4.6, available: index % 3 !== 2 })); }
export async function assignAdminRequest(input: { requestId: string; merchandiserId: string }) { void input; throw new Error("The Admin Requests assignment endpoint was not provided."); }
