export {
  AlertTriangle as WarningIcon,
  Bell as NotificationIcon,
  Boxes as BoxIcon,
  CalendarDays as CalendarIcon,
  CheckCircle2 as CheckCircleIcon,
  Check as CheckIcon,
  ChevronDown as SidebarChevronIcon,
  ChevronLeft as BackChevronIcon,
  ChevronUp as SidebarChevronUpIcon,
  CircleDollarSign as CostIcon,
  Clock3 as ClockIcon,
  CreditCard as PaymentIcon,
  Edit3 as EditIcon,
  LayoutGrid as DashboardGridIcon,
  LogOut as LogoutIcon,
  MapPin as MapPinIcon,
  NotebookTabs as CatalogIcon,
  Plus as AddIcon,
  ArrowLeft as PaginationPreviousIcon,
  ArrowRight as PaginationNextIcon,
  Star as StarIcon,
  SlidersHorizontal as FilterIcon,
  Trash2 as TrashIcon,
  UploadCloud as UploadIcon,
  UsersRound as AdminsIcon,
  RotateCcw as RestoreIcon,
  Download as DownloadIcon,
  Activity as ActivityIcon,
  Eye as ViewIcon,
  Repeat2 as RepeatIcon,
  MessageCircle as ScheduleIcon,
  X as CloseIcon,
  Building2 as CompaniesIcon,
  Users as WorkersIcon,
  TicketPercent as PromoCodeIcon,
  Settings as SettingsIcon,
  BriefcaseBusiness as ServicesIcon,
  PackageCheck as RequestsIcon,
  HandCoins as RevenueIcon,
} from "lucide-react";

export const dashboardIconKeys = [
  "dashboard",
  "box",
  "payment",
  "catalog",
  "admins",
  "trash",
  "logout",
  "chevron",
  "companies",
  "workers",
  "promoCode",
  "settings",
  "services",
] as const;

export type DashboardIconKey = (typeof dashboardIconKeys)[number];
