"use client";
import { useQueryClient } from "@tanstack/react-query";
import { useDeferredValue, useMemo, useState } from "react";
import { useLocale, useTranslations } from "next-intl";
import { useBrandsQuery } from "@/modules/company/catalog/brands/use-query";
import { useCategoriesQuery } from "@/modules/company/catalog/categories/hooks";
import { useCreateProductMutation, useDeleteProductMutation, useUpdateProductMutation } from "@/modules/company/catalog/products/use-mutations";
import { useProductsQuery } from "@/modules/company/catalog/products/use-query";
import { useProductFilterOptionsQuery } from "@/modules/company/catalog/products/use-filter-options-query";
import { useSubBrandsQuery } from "@/modules/company/catalog/sub-brands/use-query";
import { useSubCategoriesQuery } from "@/modules/company/catalog/sub-categories/hooks";
import { bulkDeleteProductsService, downloadProductsTemplateService, importProductsService } from "@/modules/company/catalog/products/service";
import type { CompanyProduct } from "@/modules/company/catalog/products/types";
import { DeleteConfirmDialog } from "@/shared/components/dashboard/delete-confirm-dialog";
import { AddIcon, FilterIcon, PaginationNextIcon, PaginationPreviousIcon, UploadIcon } from "@/shared/components/dashboard/dashboard-icons";
import { SearchInput } from "@/shared/components/dashboard/search-input";
import { normalizeApiError } from "@/shared/lib/api/errors";
import { QUERY_KEYS } from "@/shared/lib/query/keys";
import { cn } from "@/shared/lib/utils";
import { Button } from "@/shared/ui/button";
import { Input } from "@/shared/ui/input";
import { CatalogFormDialog, CatalogStatusField } from "@/modules/company/catalog/shared/form-dialog";
import { CatalogImportDialog } from "@/modules/company/catalog/shared/import-dialog";
import { CatalogProductTable } from "./table";
import { CatalogUploadArea } from "@/modules/company/catalog/shared/upload-area";
import type { ProductRow } from "@/modules/company/catalog/shared/seed";

type Dialog = "add" | "edit" | "delete" | "import" | null;
function relation(value: CompanyProduct["brand"] | CompanyProduct["sub_brand"] | CompanyProduct["category"] | CompanyProduct["sub_category"], fallback: string) { return typeof value === "string" ? value : value?.name ?? fallback; }
function activeOf(item: CompanyProduct) { return item.active ?? (item.is_active === true || item.is_active === 1 || item.is_active === "1"); }
function matchesProductName(item: CompanyProduct, search: string) { return !search || item.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()); }
function productTranslation(item: CompanyProduct, locale: "en" | "ar", field: "name" | "description") { if (Array.isArray(item.translations)) return item.translations.find((value) => value.locale === locale)?.[field] ?? (field === "name" ? item.name : item.description) ?? ""; const value = item.translations?.[locale]; if (typeof value === "string") return field === "name" ? value : item.description ?? ""; return value?.[field] ?? (field === "name" ? item.name : item.description) ?? ""; }
function relationId(direct: string | number | undefined, value: CompanyProduct["brand"] | CompanyProduct["sub_brand"] | CompanyProduct["category"] | CompanyProduct["sub_category"]) { return direct != null ? String(direct) : typeof value === "object" && value?.id != null ? String(value.id) : ""; }

export function ProductPage() {
  const t = useTranslations("dashboard"), locale = useLocale(), queryClient = useQueryClient();
  const [dialog, setDialog] = useState<Dialog>(null), [selectedId, setSelectedId] = useState<string | null>(null);
  const [brandId, setBrandId] = useState(""), [subBrandId, setSubBrandId] = useState(""), [categoryId, setCategoryId] = useState(""), [subCategoryId, setSubCategoryId] = useState("");
  const [nameEn, setNameEn] = useState(""), [nameAr, setNameAr] = useState(""), [descriptionEn, setDescriptionEn] = useState(""), [descriptionAr, setDescriptionAr] = useState(""), [sku, setSku] = useState(""), [barcode, setBarcode] = useState(""), [active, setActive] = useState(true), [image, setImage] = useState<File | null>(null), [existingImage, setExistingImage] = useState<string | null>(null);
  const [search, setSearch] = useState(""), [activeFilter, setActiveFilter] = useState<"all" | "1" | "0">("all"), [brandFilter, setBrandFilter] = useState(""), [subBrandFilter, setSubBrandFilter] = useState(""), [categoryFilter, setCategoryFilter] = useState(""), [subCategoryFilter, setSubCategoryFilter] = useState(""), [page, setPage] = useState(1);
  const [error, setError] = useState(""), [deleteError, setDeleteError] = useState(""), [success, setSuccess] = useState(""), [importFile, setImportFile] = useState<File | null>(null), [importError, setImportError] = useState(""), [importing, setImporting] = useState(false), [downloading, setDownloading] = useState(false), [downloadError, setDownloadError] = useState(""), [selectedIds, setSelectedIds] = useState<string[]>([]);
  const deferred = useDeferredValue(search.trim());
  const brands = useBrandsQuery({ per_page: 100, page: 1 });
  const subBrands = useSubBrandsQuery({ per_page: 100, page: 1, brand_id: brandId || brandFilter || undefined });
  const categories = useCategoriesQuery({ per_page: 100, page: 1, brand_id: brandId || brandFilter || undefined, sub_brand_id: subBrandId || subBrandFilter || undefined });
  const subCategories = useSubCategoriesQuery({ per_page: 100, page: 1, brand_id: brandId || brandFilter || undefined, sub_brand_id: subBrandId || subBrandFilter || undefined, category_id: categoryId || categoryFilter || undefined });
  const formOpen = dialog === "add" || dialog === "edit";
  const filterOptions = useProductFilterOptionsQuery({ brand_id: formOpen ? brandId || undefined : brandFilter || undefined, sub_brand_id: formOpen ? subBrandId || undefined : subBrandFilter || undefined, category_id: formOpen ? categoryId || undefined : categoryFilter || undefined, sub_category_id: formOpen ? subCategoryId || undefined : subCategoryFilter || undefined });
  const products = useProductsQuery({ per_page: deferred ? 100 : 10, page, active: activeFilter === "all" ? undefined : activeFilter === "1", brand_id: brandFilter || undefined, sub_brand_id: subBrandFilter || undefined, category_id: categoryFilter || undefined, sub_category_id: subCategoryFilter || undefined });
  const createMutation = useCreateProductMutation(), updateMutation = useUpdateProductMutation(), deleteMutation = useDeleteProductMutation();
  const rows = useMemo<ProductRow[]>(() => (products.data?.data ?? []).filter((x) => matchesProductName(x, search.trim())).map((x) => ({ id: String(x.id), name: x.name, thumbnailAlt: x.name, thumbnailUrl: x.image_url ?? x.image ?? x.logo_url ?? x.logo ?? null, pathSegments: [relation(x.brand, `#${x.brand_id}`), relation(x.sub_brand, `#${x.sub_brand_id}`), relation(x.category, `#${x.category_id}`), relation(x.sub_category, `#${x.sub_category_id}`)], sku: x.sku, description: x.description ?? "-", isActive: activeOf(x), statusDisplay: "toggle", createdDate: x.created_at ? new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" }).format(new Date(x.created_at)) : "-" })), [locale, products.data?.data, search]);
  const current = products.data?.meta?.current_page ?? page, last = Math.max(products.data?.meta?.last_page ?? 1, 1), pages = useMemo(() => Array.from({ length: Math.min(last, 5) }, (_, i) => Math.max(1, Math.min(current - 2, last - Math.min(last, 5) + 1)) + i), [current, last]);
  const close = () => { setDialog(null); setSelectedId(null); setError(""); setDeleteError(""); };
  const refresh = () => queryClient.invalidateQueries({ queryKey: QUERY_KEYS.products() });
  const add = () => { setBrandId(""); setSubBrandId(""); setCategoryId(""); setSubCategoryId(""); setNameEn(""); setNameAr(""); setDescriptionEn(""); setDescriptionAr(""); setSku(""); setBarcode(""); setActive(true); setImage(null); setExistingImage(null); setDialog("add"); };
  async function save() { if (!brandId || !subBrandId || !categoryId || !subCategoryId || !nameEn.trim() || !nameAr.trim() || !sku.trim() || !barcode.trim() || (dialog === "add" && !image)) { setError(t("catalogPage.product.dialog.requiredFields")); return; } try { const payload = { brandId, subBrandId, categoryId, subCategoryId, nameEn: nameEn.trim(), nameAr: nameAr.trim(), descriptionEn: descriptionEn.trim(), descriptionAr: descriptionAr.trim(), sku: sku.trim(), barcode: barcode.trim(), isActive: active, image: image ?? undefined }; const response = dialog === "edit" && selectedId ? await updateMutation.mutateAsync({ id: selectedId, payload }) : await createMutation.mutateAsync(payload); setSuccess(response.message); await refresh(); close(); } catch (value) { setError(normalizeApiError(value).message); } }
  function edit(id: string) { const x = products.data?.data.find((value) => String(value.id) === id); if (!x) return; setSelectedId(id); setBrandId(relationId(x.brand_id, x.brand)); setSubBrandId(relationId(x.sub_brand_id, x.sub_brand)); setCategoryId(relationId(x.category_id, x.category)); setSubCategoryId(relationId(x.sub_category_id, x.sub_category)); setNameEn(productTranslation(x, "en", "name")); setNameAr(productTranslation(x, "ar", "name")); setDescriptionEn(productTranslation(x, "en", "description")); setDescriptionAr(productTranslation(x, "ar", "description")); setSku(x.sku); setBarcode(x.barcode ?? ""); setActive(activeOf(x)); setImage(null); setExistingImage(x.image_url ?? x.image ?? x.logo_url ?? x.logo ?? null); setDialog("edit"); }
  async function remove() { const ids = selectedId ? [selectedId] : selectedIds; if (!ids.length) return; try { const response = ids.length === 1 ? await deleteMutation.mutateAsync(ids[0]) : await bulkDeleteProductsService(ids); setSuccess(response.message); setSelectedIds([]); await refresh(); close(); } catch (value) { setDeleteError(normalizeApiError(value).message); } }
  async function upload() { if (!importFile) { setImportError(t("catalogPage.product.dialog.importFileRequired")); return; } setImporting(true); try { const response = await importProductsService(importFile); setSuccess(response.message); await refresh(); close(); } catch (value) { setImportError(normalizeApiError(value).message); } finally { setImporting(false); } }
  async function download() { setDownloading(true); setDownloadError(""); try { await downloadProductsTemplateService(); } catch (value) { setDownloadError(normalizeApiError(value).message); } finally { setDownloading(false); } }
  const labels = { products: t("catalogPage.product.table.columns.products"), family: t("catalogPage.product.table.columns.family"), sku: t("catalogPage.product.table.columns.sku"), description: t("catalogPage.product.table.columns.description"), status: t("catalogPage.table.columns.status"), createdDate: t("catalogPage.table.columns.createdDate"), action: t("catalogPage.table.columns.action"), selectAll: t("catalogPage.table.actions.selectAll"), selectRow: t("catalogPage.table.actions.selectRow"), delete: t("catalogPage.table.actions.delete"), edit: t("catalogPage.table.actions.edit"), toggleStatus: t("catalogPage.table.actions.toggleStatus"), activeLabel: t("catalogPage.status.active"), inactiveLabel: t("catalogPage.status.inactive") };
  const brandOptions = filterOptions.data?.brands ?? brands.data?.data ?? [];
  const selectedParentBrand = formOpen ? brandId : brandFilter, selectedParentSubBrand = formOpen ? subBrandId : subBrandFilter, selectedParentCategory = formOpen ? categoryId : categoryFilter;
  const subBrandOptions = filterOptions.data?.sub_brands ?? (subBrands.data?.data ?? []).filter((item) => !selectedParentBrand || String(item.brand_id ?? (typeof item.brand === "object" ? item.brand?.id : "")) === selectedParentBrand);
  const categoryOptions = filterOptions.data?.categories ?? (categories.data?.data ?? []).filter((item) => !selectedParentSubBrand || String(item.sub_brand_id ?? (typeof item.sub_brand === "object" ? item.sub_brand?.id : "")) === selectedParentSubBrand);
  const subCategoryOptions = filterOptions.data?.sub_categories ?? (subCategories.data?.data ?? []).filter((item) => !selectedParentCategory || String(item.category_id ?? (typeof item.category === "object" ? item.category?.id : "")) === selectedParentCategory);
  const select = (value: string, set: (x: string) => void, placeholder: string, options: { id: string | number; name?: string }[], disabled = false) => { const blocked = disabled || (options === subBrandOptions && !selectedParentBrand) || (options === categoryOptions && !selectedParentSubBrand) || (options === subCategoryOptions && !selectedParentCategory); return <select value={value} onChange={(e) => set(e.target.value)} disabled={blocked} className="h-11 rounded-lg border bg-card px-3 disabled:cursor-not-allowed disabled:opacity-50"><option value="">{placeholder}</option>{options.map((x) => <option key={x.id} value={x.id}>{x.name ?? `#${x.id}`}</option>)}</select>; };

  return <div className="space-y-6 px-4 py-8 lg:px-8"><div className="flex justify-between"><div><h1 className="text-3xl font-bold">{t("catalogPage.product.title")}</h1><p className="mt-2 text-lg text-muted-foreground">{t("catalogPage.product.subtitle")}</p></div><div className="flex gap-3"><Button variant="outline" onClick={() => { setImportFile(null); setImportError(""); setDialog("import"); }}><UploadIcon className="size-4" />{t("catalogPage.actions.import")}</Button><Button onClick={add}><AddIcon className="size-4" />{t("catalogPage.product.actions.add")}</Button></div></div>
    {success ? <p className="rounded-xl border border-success/20 bg-success/10 px-4 py-3 text-success">{success}</p> : null}
    <div className="flex flex-wrap gap-3"><SearchInput label={t("catalogPage.search.label")} placeholder={t("catalogPage.search.placeholder")} className="max-w-[400px]" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} />{select(brandFilter, (x) => { setBrandFilter(x); setSubBrandFilter(""); setCategoryFilter(""); setSubCategoryFilter(""); }, t("catalogPage.dialog.parentBrand"), brandOptions)}{select(subBrandFilter, (x) => { setSubBrandFilter(x); setCategoryFilter(""); setSubCategoryFilter(""); }, t("catalogPage.dialog.subBrand"), subBrandOptions)}{select(categoryFilter, (x) => { setCategoryFilter(x); setSubCategoryFilter(""); }, t("catalogPage.product.dialog.categoryLabel"), categoryOptions)}{select(subCategoryFilter, setSubCategoryFilter, t("catalogPage.product.dialog.subCategoryLabel"), subCategoryOptions)}<label className="relative"><FilterIcon className="absolute start-3 top-1/2 size-4 -translate-y-1/2" /><select value={activeFilter} onChange={(e) => setActiveFilter(e.target.value as "all" | "1" | "0")} className="h-11 rounded-lg border ps-9"><option value="all">{t("catalogPage.filters.allStatuses")}</option><option value="1">{t("catalogPage.status.active")}</option><option value="0">{t("catalogPage.status.inactive")}</option></select></label></div>
    {selectedIds.length ? <div className="flex justify-end"><Button variant="destructive" onClick={() => { setSelectedId(null); setDialog("delete"); }}>{t("catalogPage.table.actions.delete")} ({selectedIds.length})</Button></div> : null}
    {products.isError ? <p className="rounded-xl border border-destructive/20 bg-destructive/10 px-4 py-3 text-destructive">{normalizeApiError(products.error).message}</p> : <div className={cn(products.isFetching && "opacity-60")}><CatalogProductTable rows={rows} labels={labels} onDelete={(id) => { setSelectedId(id); setDialog("delete"); }} onEdit={edit} selectedIds={selectedIds} onSelectionChange={setSelectedIds} /></div>}
    <div className="flex justify-between"><Button variant="outline" disabled={current <= 1} onClick={() => setPage((x) => x - 1)}><PaginationPreviousIcon className="size-4" />{t("catalogPage.pagination.previous")}</Button><div>{pages.map((x) => <Button key={x} variant="ghost" className={cn(x === current && "bg-primary/20")} onClick={() => setPage(x)}>{x}</Button>)}</div><Button variant="outline" disabled={current >= last} onClick={() => setPage((x) => x + 1)}>{t("catalogPage.pagination.next")}<PaginationNextIcon className="size-4" /></Button></div>
    <DeleteConfirmDialog isOpen={dialog === "delete"} title={t("catalogPage.product.deleteDialog.title")} descriptionLine1={t("catalogPage.product.deleteDialog.descriptionLine1")} descriptionLine2={t("catalogPage.product.deleteDialog.descriptionLine2")} cancelLabel={t("catalogPage.product.deleteDialog.cancel")} confirmLabel={t("catalogPage.product.deleteDialog.confirm")} onClose={close} onConfirm={remove} isPending={deleteMutation.isPending} errorMessage={deleteError} />
    <CatalogFormDialog isOpen={dialog === "add" || dialog === "edit"} title={dialog === "edit" ? t("catalogPage.product.dialog.editTitle") : t("catalogPage.product.dialog.title")} closeLabel={t("catalogPage.dialog.close")} cancelLabel={t("catalogPage.dialog.cancel")} saveLabel={t("catalogPage.dialog.save")} onClose={close} onSubmit={save} isPending={createMutation.isPending || updateMutation.isPending} errorMessage={error}><CatalogUploadArea label={t("catalogPage.product.dialog.uploadLabel")} hint={t("catalogPage.dialog.uploadHint")} file={image} onFileChange={setImage} existingImageUrl={dialog === "edit" ? existingImage : undefined} /><div className="grid grid-cols-2 gap-4">{select(brandId, (x) => { setBrandId(x); setSubBrandId(""); setCategoryId(""); setSubCategoryId(""); }, t("catalogPage.dialog.selectBrand"), brandOptions)}{select(subBrandId, (x) => { setSubBrandId(x); setCategoryId(""); setSubCategoryId(""); }, t("catalogPage.dialog.selectSubBrand"), subBrandOptions)}{select(categoryId, (x) => { setCategoryId(x); setSubCategoryId(""); }, t("catalogPage.product.dialog.selectCategory"), categoryOptions)}{select(subCategoryId, setSubCategoryId, t("catalogPage.product.dialog.selectSubCategory"), subCategoryOptions)}</div><div className="grid grid-cols-2 gap-4"><Input value={nameEn} onChange={(e) => setNameEn(e.target.value)} placeholder="Product name (English)" /><Input dir="rtl" value={nameAr} onChange={(e) => setNameAr(e.target.value)} placeholder="اسم المنتج (العربية)" /></div><div className="grid grid-cols-2 gap-4"><Input value={sku} onChange={(e) => setSku(e.target.value)} placeholder={t("catalogPage.product.dialog.skuPlaceholder")} /><Input value={barcode} onChange={(e) => setBarcode(e.target.value)} placeholder="Barcode" /></div><div className="grid grid-cols-2 gap-4"><textarea value={descriptionEn} onChange={(e) => setDescriptionEn(e.target.value)} rows={3} className="w-full rounded-lg border bg-secondary p-3" placeholder="Description (English)" /><textarea dir="rtl" value={descriptionAr} onChange={(e) => setDescriptionAr(e.target.value)} rows={3} className="w-full rounded-lg border bg-secondary p-3" placeholder="الوصف (العربية)" /></div><CatalogStatusField activeLabel={t("catalogPage.dialog.statusActive")} description={t("catalogPage.product.dialog.statusDescription")} ariaLabel={t("catalogPage.dialog.statusActive")} isActive={active} onChange={setActive} /></CatalogFormDialog>
    <CatalogImportDialog isOpen={dialog === "import"} title={t("catalogPage.import.title")} description={t("catalogPage.import.description")} downloadLabel={t("catalogPage.import.downloadLabel")} uploadLabel={t("catalogPage.import.uploadLabel")} uploadHint={t("catalogPage.import.uploadHint")} uploadFormat={t("catalogPage.import.uploadFormat")} cancelLabel={t("catalogPage.dialog.cancel")} saveLabel={t("catalogPage.dialog.save")} closeLabel={t("catalogPage.dialog.close")} onClose={close} onDownload={download} isDownloading={downloading} downloadError={downloadError} selectedFile={importFile} onFileChange={setImportFile} onImport={upload} isImporting={importing} importError={importError} />
  </div>;
}
