import type { GetBrandsMeta } from "@/modules/company/catalog/brands/types";
import type { CompanyCategory, GetCategoriesParams, GetCategoriesResponse } from "@/modules/company/catalog/categories/types";
import { apiClient } from "@/shared/lib/api/client";
import { CATALOG_IMAGE_REMOVE_FILE_NAME } from "@/shared/components/catalog/upload-area";

type Page = Partial<GetBrandsMeta> & { data: CompanyCategory[]; meta?: GetBrandsMeta };
type Raw = Omit<GetCategoriesResponse, "data"> & { data: CompanyCategory[] | Page; pagination?: GetBrandsMeta };
export async function getCategoriesService(params: GetCategoriesParams): Promise<GetCategoriesResponse> { const { data: payload } = await apiClient.get<Raw>("/api/company/categories", { params }); if (Array.isArray(payload.data)) return payload as GetCategoriesResponse; const value = payload.data; return { success: payload.success, message: payload.message, data: value.data, meta: value.meta ?? payload.pagination ?? (value.current_page != null && value.last_page != null ? { current_page: value.current_page, last_page: value.last_page, per_page: value.per_page ?? 10, total: value.total ?? value.data.length } : undefined) }; }
export interface CategoryPayload { brandId: string; subBrandId: string; nameEn: string; nameAr: string; isActive: boolean; image?: File; logoAction?: "keep" | "remove" | "replace"; }
function form(payload: CategoryPayload, update = false) { const data = new FormData(); const removeImage = payload.image?.name === CATALOG_IMAGE_REMOVE_FILE_NAME; data.append("translations[en][name]", payload.nameEn); data.append("translations[ar][name]", payload.nameAr); data.append("is_active", payload.isActive ? "1" : "0"); data.append("brand_id", payload.brandId); data.append("sub_brand_id", payload.subBrandId); if (update) { data.append("_method", "put"); data.append("logo_action", removeImage ? "remove" : payload.logoAction ?? (payload.image ? "replace" : "keep")); } if (payload.image && !removeImage) data.append("image", payload.image, payload.image.name); return data; }
const multipart = { headers: { "Content-Type": "multipart/form-data" } };
export async function createCategoryService(payload: CategoryPayload) { return (await apiClient.post("/api/company/categories", form(payload), multipart)).data as { success: boolean; message: string }; }
export async function updateCategoryService({ id, payload }: { id: string; payload: CategoryPayload }) { return (await apiClient.post(`/api/company/categories/${encodeURIComponent(id)}`, form(payload, true), multipart)).data as { success: boolean; message: string }; }
export async function deleteCategoryService(id: string) { return (await apiClient.delete(`/api/company/categories/${encodeURIComponent(id)}`)).data as { success: boolean; message: string }; }
export async function importCategoriesService(file: File) { const data = new FormData(); data.append("file", file, file.name); return (await apiClient.post("/api/company/categories/excel/import", data, multipart)).data as { success: boolean; message: string }; }
export async function downloadCategoriesTemplateService() { const response = await apiClient.get<Blob>("/api/company/categories/excel/template", { responseType: "blob" }); const disposition = response.headers["content-disposition"] as string | undefined; const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = disposition?.match(/filename="?([^";]+)"?/i)?.[1] ?? "categories-template.xlsx"; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); }
