export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  verifyEmail: "/verify-email",
  forgotPassword: "/forgot-password",
  otpVerification: "/otp-verification",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  dashboardRequests: "/dashboard/requests",
  dashboardCreateRequest: "/dashboard/requests/create",
  dashboardPayment: "/dashboard/payment",
  dashboardCatalog:            "/dashboard/catalog",
  dashboardCatalogBrand:       "/dashboard/catalog/brand",
  dashboardCatalogSubBrand:    "/dashboard/catalog/sub-brand",
  dashboardCatalogCategory:    "/dashboard/catalog/category",
  dashboardCatalogSubCategory: "/dashboard/catalog/sub-category",
  dashboardCatalogProduct:     "/dashboard/catalog/product",
  dashboardAdmins: "/dashboard/admins",
  dashboardTrash: "/dashboard/trash",
  adminDashboard: "/admin",
  adminLogin: "/admin/login",
  adminForgotPassword: "/admin/forgot-password",
  adminOtpVerification: "/admin/otp-verification",
  adminResetPassword: "/admin/reset-password",
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
