import type { GetBrandsMeta } from "@/modules/dashboard/types/brand";
import type { CompanySubCategory, GetSubCategoriesParams, GetSubCategoriesResponse } from "@/modules/dashboard/types/sub-category";
import { apiClient } from "@/shared/lib/api/client";
type Page = Partial<GetBrandsMeta> & { data: CompanySubCategory[]; meta?: GetBrandsMeta };
type Raw = Omit<GetSubCategoriesResponse, "data"> & { data: CompanySubCategory[] | Page; pagination?: GetBrandsMeta };
export async function getSubCategoriesService(params: GetSubCategoriesParams): Promise<GetSubCategoriesResponse> { const { data: payload } = await apiClient.get<Raw>("/api/company/sub-categories", { params }); if (Array.isArray(payload.data)) return payload as GetSubCategoriesResponse; const value = payload.data; return { success: payload.success, message: payload.message, data: value.data, meta: value.meta ?? payload.pagination ?? (value.current_page != null && value.last_page != null ? { current_page: value.current_page, last_page: value.last_page, per_page: value.per_page ?? 10, total: value.total ?? value.data.length } : undefined) }; }
export interface SubCategoryPayload { brandId: string; subBrandId: string; categoryId: string; nameEn: string; nameAr: string; isActive: boolean; image?: File; }
function form(payload: SubCategoryPayload, update = false) { const data = new FormData(); data.append("translations[en][name]", payload.nameEn); data.append("translations[ar][name]", payload.nameAr); data.append("is_active", payload.isActive ? "1" : "0"); data.append("brand_id", payload.brandId); data.append("sub_brand_id", payload.subBrandId); data.append("category_id", payload.categoryId); if (update) data.append("_method", "put"); if (payload.image) data.append("image", payload.image, payload.image.name); return data; }
const multipart = { headers: { "Content-Type": "multipart/form-data" } };
export async function createSubCategoryService(payload: SubCategoryPayload) { return (await apiClient.post("/api/company/sub-categories", form(payload), multipart)).data as { success: boolean; message: string }; }
export async function updateSubCategoryService({ id, payload }: { id: string; payload: SubCategoryPayload }) { return (await apiClient.post(`/api/company/sub-categories/${encodeURIComponent(id)}`, form(payload, true), multipart)).data as { success: boolean; message: string }; }
export async function deleteSubCategoryService(id: string) { return (await apiClient.delete(`/api/company/sub-categories/${encodeURIComponent(id)}`)).data as { success: boolean; message: string }; }
export async function importSubCategoriesService(file: File) { const data = new FormData(); data.append("file", file, file.name); return (await apiClient.post("/api/company/sub-categories/excel/import", data, multipart)).data as { success: boolean; message: string }; }
export async function downloadSubCategoriesTemplateService() { const response = await apiClient.get<Blob>("/api/company/sub-categories/excel/template", { responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = (response.headers["content-disposition"] as string | undefined)?.match(/filename="?([^";]+)"?/i)?.[1] ?? "sub-categories-template.xlsx"; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); }
